# Generated by Django 5.2.6 on 2025-10-04 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('idModel', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('filePath', models.FileField(upload_to='files/datasets/', verbose_name='File')),
                ('parameters', models.FileField(upload_to='files/models/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
            },
        ),
    ]
