# Generated by Django 5.2.6 on 2025-10-05 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('idChatbot', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('chatbot_info', models.JSONField(blank=True, null=True, verbose_name='Chatbot Info')),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
            },
        ),
    ]
