# Generated by Django 5.2.6 on 2025-10-04 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('idUserData', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('name_dataset', models.CharField(max_length=100, verbose_name='Name')),
                ('filePath', models.FileField(upload_to='datasets/', verbose_name='File')),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User dataset',
                'verbose_name_plural': 'User datasets',
            },
        ),
    ]
