# Generated by Django 5.2.6 on 2025-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('passEncrypted', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
